components:
- type: ColumnPanel
  properties: {role: null, tooltip: '', border: '', foreground: '', visible: true,
    wrap_on: mobile, col_spacing: medium, spacing_above: small, col_widths: '{}',
    spacing_below: small, background: ''}
  name: card_1
  layout_properties: {grid_position: 'VPIBHG,EIBQKD'}
  event_bindings: {}
  components:
  - type: RepeatingPanel
    properties: {role: null, tooltip: '', border: '', foreground: '', items: null,
      visible: true, spacing_above: small, spacing_below: small, item_template: EnvironmentShortForm,
      background: ''}
    name: repeating_panel_1
    layout_properties: {grid_position: 'VYWZAF,OYLZCP'}
    event_bindings: {}
container:
  type: ColumnPanel
  event_bindings: {}
  properties: {role: null, tooltip: '', border: '', foreground: '', visible: true,
    wrap_on: never, col_spacing: medium, spacing_above: small, col_widths: '{}', spacing_below: small,
    background: ''}
